export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const SIGNIN_USER = "SIGNIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

