export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNIN_USER_FAIL = "SIGNIN_USER_FAIL";
export const SIGNIN_USER = "SIGNIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const GET_PROFILE_PICTURE = "GET_PROFILE_PICTURE";
export const GET_CURRENT_USER="GET_CURRENT_USER";

